name: Push to PyPI

on:
  release:
    types: [released, prereleased]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8 - 3.12'
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.2.2
    - name: Install dependencies
      run: |
        poetry install
        pip list
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: Update Version
      run: |
        poetry version ${{ env.RELEASE_VERSION }}
    - name: Build Library
      run: |
        poetry build
    - name: Publish to PyPI
      run: |
        poetry config pypi-token.pypi ${{ secrets.pypi_password_servicex }}
        poetry publish

  build-docs:
    needs:
      - publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - uses: abatilo/actions-poetry@v2.1.3
      with:
        poetry-version: "1.2.2"
    - name: install
      run: poetry install  -E docs
    - name: Build documentation
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        cd docs/
        poetry run sphinx-build -b html . _build
        cp -r _build/* ../gh-pages/
    - name: Deploy documentation
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: gh-pages


